[package]
name = "precisionTesterOnRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f128 = "0.2.9"
rug = "1.17"
num="0.1.27"
num-complex = "0.3.1"